# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==22.8.23, flake8-docstrings==1.6.0]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-pyyaml, types-psutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

# Security checks
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: [--recursive, --configfile, .bandit.yml]
        exclude: ^tests/

# Format Python imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

# Check for security vulnerabilities
-   repo: https://github.com/pyupio/safety
    rev: 2.3.5
    hooks:
    -   id: safety
        args: [--full-report]
        pass_filenames: false

# Check for outdated dependencies
-   repo: local
    hooks:
    -   id: check-dependencies
        name: Check for outdated dependencies
        entry: bash -c "poetry update --dry-run"
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]

# Run tests
-   repo: local
    hooks:
    -   id: pytest
        name: Run tests
        entry: bash -c "pytest -v"
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]

# Run dependency checking script
-   repo: local
    hooks:
    -   id: check-dependencies
        name: Check Python dependencies
        entry: python scripts/check_dependencies.py
        language: system
        always_run: true
        pass_filenames: false
        stages: [commit, push]
